In [1]:
import numpy as np

i = np.array([1, 2, 3, 4, 5, 6 ])

print(i)

[1 2 3 4 5 6]


In [2]:
i = np.array([10,20,30,40,50])

print(i[0])

10


In [4]:
i = np.array([
    [10,20,30,40,50],
    [60,70,80,90,100],
])

print(i[1,1])

70


In [5]:
print(i[0,4])

50


In [6]:
i = np.array([
    [[10,20,30],[40,50,60]],
    [[70,80,90],[100,110,120]]
])

print(i[0,1,2])

60


In [7]:
print(i[1,1,2])

120


In [10]:
print(i[1,1,-1])

120


In [11]:
print(i[1,-2,-1])

90


In [12]:
print(i[1, -2, -1])

90


In [13]:
i = np.array([10,20,30,40,50,60])

print(i[-1])

60


In [14]:
print(i[0:3])

[10 20 30]


In [15]:
i = np.array([10,20,30,40,50,60,70,80])

print(i[3:6])

[40 50 60]


In [16]:
print(i[3:6])

[40 50 60]


In [17]:
print(i[2:])

[30 40 50 60 70 80]


In [18]:
print(i[:6])

[10 20 30 40 50 60]


In [19]:
print(i[-5:-2])

[40 50 60]


In [20]:
print(i[-3:-1])

[60 70]


In [21]:
print(i[2:-3])

[30 40 50]


In [22]:
i = np.array([10,20,30,40,50,60,70,80])

print(i[0:4:2])

[10 30]


In [23]:
print(i[0:7:3])

[10 40 70]


In [24]:
print(i[::])

[10 20 30 40 50 60 70 80]


In [25]:
print(i[::2])

[10 30 50 70]


In [26]:
i = np.array([
    [10,20,30,40,50],
    [60,70,80,90,100],
])

print(i[1,0:3])

[60 70 80]


In [27]:
print(i[0,1:4])

[20 30 40]


In [33]:
i = np.array([
    [10,20,30,40,50],
    [60,70,80,90,100],
    [11,22,33,44,55],
])

print(i[2,2:4])

[33 44]


In [34]:
print(i[0:2,1])

[20 70]


In [30]:
i = np.array([
    [10,20,30,40,50],
    [60,70,80,90,100],
    [11,22,33,44,55],
    [1,2,3,4,5],
])

print(i[0:3,2])

[30 80 33]


In [31]:
print(i[0:4,0:2])

[[10 20]
 [60 70]
 [11 22]
 [ 1  2]]


In [32]:
print(i[0:2,2:4])

[[30 40]
 [80 90]]


In [35]:
i = np.array([
    [10,20,30,40,50],
    [60,70,80,90,100],
    [11,22,33,44,55],
    [1,2,3,4,5],
])

print(i[0:3,-3:-1])

[[30 40]
 [80 90]
 [33 44]]


In [36]:
import numpy as np

i = np.array([10,20,30,40,50])

print(i.dtype)

int32


In [38]:
import numpy as np

i = np.array([10.1,20.2,30.3])

i1 = i.astype('i')

print(i1)

print(i1.dtype)

print(i)

[10 20 30]
int32
[10.1 20.2 30.3]


In [39]:
i = np.array([10.,20.,30.])

i1 = i.astype('f')

print(i1)

print(i1.dtype)

[10. 20. 30.]
float32


In [40]:
i = np.array([10,20,30])

i1 = i.astype('int')

print(i1)

print(i1.dtype)

[10 20 30]
int32


In [42]:
i = np.array([10.1,20,30.3,40,60.30,0])

i1 = i.astype('bool')

print(i1)

print(i1.dtype)

[ True  True  True  True  True False]
bool
